### ISSUE TITLE
SMART CONTRACT: write Withdraw Token function

### ISSUE THREAD

**Issue by Dprof-in-tech** [Dprof-in-tech/peer-on-strk#12]
Write a withdraw token function that would withraw tokens from the contract to the caller's wallet.

**Comment by TEMHITHORPHE** [comment]
Mind if I try this one?.
° Check to make sure caller is a depositor.
° Check to make sure token is supported, and that caller deposited with the token in question.
° Check to make sure token amount does not overdraft.

ETA: 1 day.

**Comment by ShantelPeters** [comment]
Can i please be assigned to this issue

**Comment by mimiprosper** [comment]
May I take this issue on?

**Comment by GideonBature** [comment]
Can this be assigned to me please, I just rounded the Starknet Cairo bootcamp, where I have written various contracts including unit and integration tests.

This will help me apply all what I have learnt to good use.

**Comment by sandragcarrillo** [comment]
Would love to contribute on this issue

My background and how it can be leveraged
I have been learning Cairo for the past months and i'm currently helping to improve Nethermind's projects related to Starknet educational projects so I have been writing simple smart contracts in the past weeks. It would be awesome to contribute writing this function so I can practice in a real project all the knowledgeI have been getting.

How I plan on tackling this issue
I would write a function to withdraw tokens, making sure it's only available to depositors and allow them to withdraw their desired amount from the contract. Also making sure that the amount they withdraw is not higher than the amount they already have deposited.

**Comment by jsanchez556** [comment]
My background and how it can be leveraged

Hello, I’m Jose Mario from Costa Rica. With over 15 years of experience in development, I am passionate about contributing to open-source projects and currently expanding my skill set with Rust, Cairo, and Solidity, participated in ODHacks since 7.0 as part of my involvement with Dojo Coding. I am eager to apply my extensive experience and newly acquired skills to new challenges and innovative projects.

Approach to Address the Issue:

To implement the `withdrawToken` function in the contract, I will follow these steps:

1. Retrieve caller address to identify the wallet address of the caller initiating the withdrawal.
2. Check the caller’s token balance to ensure they have sufficient tokens available for withdrawal.
3. Subtract the specified withdrawal amount from the caller’s balance to maintain accurate token tracking in the contract’s storage.
4. Execute token transfer function to securely transfer the requested token amount from the contract to the caller's wallet address.

**Comment by blessingbytes** [comment]
Would love to tackle it

**Comment by SoarinSkySagar** [comment]
GM @Dprof-in-tech, I am Sagar Rana, a smart contract developer and full stack engineer. I have 3 years of experience building robust full stack applications and over a year of writing smart contracts. I use mainly Solidity, Rust and Cairo for my smart contracts, and I have been building on Starknet ecosystem for the past few months and have honed my Cairo skills. Here is how I would approach this issue:

 ## My Approach to this problem:
I would firstly add the withdraw function interface in the `interfaces/ipeer_protocol.cairo` like this:
```
fn withdraw(ref self: TContractState, token_address: ContractAddress, amount: u256);
```
Then as the next step I will go to `peer_protocol.cairo` and implement the withdraw function there. I will use `get_caller_address()` to get the caller's address and transfer the tokens from the contract (got using `get_contract_address()` to the caller. Then I will add a new field to Storage called `token_withdraws` which will be of type `Map<(ContractAddress, ContractAddress), u256>`. Once the token is withdrawn, it will be recorded in the Map. I will also create a new Event to be emitted once a token has been withdrawn.
Lastly, I will add new tests to check the withdraw feature and make sure all tests are passing before creating the PR.

## ETA: 1 day

**Comment by Yunusabdul38** [comment]
Could I grab this task?

**Comment by casweeney** [comment]
Looking at the smart contract, users can deposit only supported tokens meaning users can deposit multiple tokens that are supported. 

The `withdraw()` function will take in same arguments like the `deposit()` function. That is `token_address` and `amount`.

With these arguments, I will check the contract, to ensure that the caller has some deposited balance and also ensure that the withdraw amount is not more that their deposits for a specified token. From the user's balance.  I will deduct the withdrawal amount then I will transfer the amount of token specified to the user calling the `withdraw()`function.

After which I will emit a `WithdrawalSuccessful` event.

**Comment by Gerson2102** [comment]
### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other Cairo projects like:

- `Raito`
- `kakarot-ssj`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by jaiminRaiyani** [comment]
May I pick this up?

**Comment by martinvibes** [comment]
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Please kindly assign :)

**Comment by Kaminar-i** [comment]
Please can solve this issue with my contribution

**Comment by Kaminar-i** [comment]
Please can I be given the opportunity to work on this issue with my contribution

**Comment by aniruddhaaps** [comment]
I'm a cairo dev. A new-comer here, willing to and ready to contribute to solve the issue.

**Comment by PoulavBhowmick03** [comment]
I’d like to resolve this.
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and [OnlyDust Profile](https://app.onlydust.com/u/PoulavBhowmick03). Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.

### Approach

I will write the withdraw_token function to allow users to withdraw tokens from the contract to their wallet.
- I will define the withdraw function with parameters for the withdrawal amount and t the address of the token. it will verify that the caller has enough balance to proceed with the withdrawal.
- I will add logic to check if the caller's wallet balance within the contract is sufficient for the requested withdrawal amount. This will prevent errors due to insufficient balance.
- If the balance check passes, the function will deduct the specified amount from the caller’s balance stored in the contract.
- I will use Cairo's syntax for token transfer to move the specified amount from the contract to the caller's wallet.

Event Emission: After the transfer, I'll emit an event for the withdraw with details like the caller's address and the amount withdrawn

ETA - 2 days
Thanks! Would love to work on this

**Comment by Dprof-in-tech** [comment]
@PoulavBhowmick03 , please look through the already built deposit function and build the withdraw function.

**Comment by PoulavBhowmick03** [comment]
> @PoulavBhowmick03 , please look through the already built deposit function and build the withdraw function.

Sure! will go through that!
